idea:
    build: .
    labels:
        org.kurron.description: "JetBrains Base Image"
    container_name: "jebrains-base"
    net: "host"
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/vagrant:/home/developer
    environment:
        DISPLAY: unix:0.0
    user: 1000:1000
